apiVersion: apps/v1
kind: Deployment
metadata:
  name: horilla-db
  namespace: horilla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: horilla-db
  template:
    metadata:
      labels:
        app: horilla-db
    spec:
      containers:
      - name: postgres
        image: postgres:16-bullseye
        env:
        - name: POSTGRES_DB
          value: horilla
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
