# Unique identifier for the project
sonar.projectKey=govindhan-ravi_horilla
sonar.organization=govindhan-ravi

# This is the name and version displayed in the SonarCloud UI
sonar.projectName=Horilla HRMS
sonar.projectVersion=1.0

# Path to sources
sonar.sources=.
sonar.exclusions=**/migrations/**, **/static/**, **/media/**

# Language specific settings
sonar.python.version=3
sonar.language=python

# Encoding of the source code
sonar.sourceEncoding=UTF-8
