FROM nginx:alpine

# Copy static files to nginx html folder
COPY static /usr/share/nginx/html/static

# Copy custom nginx config
COPY kube-docs/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
